version: "3.7"

services:
    app:
        container_name: laravel-appetite
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - appetite-net
        mem_limit: 512m  
        mem_reservation: 256m  
        cpus: 0.5  

    nginx:
        image: nginx:alpine
        container_name: nginx-appetite
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - appetite-net
        mem_limit: 512m  
        mem_reservation: 256m  
        cpus: 0.5  

    db:
        image: postgres:14
        container_name: postgres-appetite
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - appetite_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        networks:
            - appetite-net
        mem_limit: 2g  
        mem_reservation: 1g  
        cpus: 2.0

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-appetite
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - appetite-net
        restart: always
        mem_limit: 512m  
        mem_reservation: 256m  
        cpus: 0.5  

    redis:
        image: redis:latest
        container_name: redis-appetite
        volumes:
            - redis_data:/data  
        networks:
            - appetite-net
        mem_limit: 1024m    
        mem_reservation: 512m  
        cpus: 0.5

volumes:
    appetite_data:
        name: appetite_data  
    redis_data:
        name: redis_data     

networks:
    appetite-net:
        driver: bridge
